import 'package:drift/drift.dart';

/// Every table gets a UUIDv7 primary key (§22.5, §0.4). UUIDv7 is
/// time-ordered, so ids sort chronologically without a separate
/// `created_at` index — useful once export/import merges by id (§0.5).
///
/// The id has no `clientDefault`: it's generated by the repository layer
/// at insert time (`Uuid().v7()`, matching `nourishly_data`'s `uuid`
/// dependency), not by the schema. That arrives with the DAOs in Phase 2.
mixin Identifiable on Table {
  TextColumn get id => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Scopes a row to the local profile that owns it (§0.4). Every query in a
/// multi-profile app filters by this column; there is no other isolation
/// mechanism because there is no server-side row-level security to lean on.
mixin Owned on Table {
  TextColumn get ownerId =>
      text().customConstraint('NOT NULL REFERENCES users (id)')();
}

/// `created_at` / `updated_at`, kept per §0.4 even though the sync columns
/// they used to accompany (`sync_state`, `server_revision`, `device_id`)
/// were dropped — they cost nothing and make export/import merges correct.
mixin Timestamped on Table {
  DateTimeColumn get createdAt =>
      dateTime().clientDefault(() => DateTime.now())();

  DateTimeColumn get updatedAt =>
      dateTime().clientDefault(() => DateTime.now())();
}

/// A tombstone column. Null means live; set means soft-deleted. Never a
/// hard delete for anything a log entry might reference (I-6), and this is
/// also what makes export/import merges detect deletions (§0.5).
mixin SoftDeletable on Table {
  DateTimeColumn get deletedAt => dateTime().nullable()();
}
